# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RevanchasLT
                                 A QGIS plugin
 Plugin para análisis de perfiles topográficos de muros de contención
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-01-01
        copyright            : (C) 2024 by Las Tortolas Project
        email                : support@lastortolas.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load RevanchasLT class from file RevanchasLT.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .revanchas_lt_plugin import RevanchasLT
    return RevanchasLT(iface)